/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule User_user.graphql
 * @generated SignedSource<<4a70381454c4465ab2e17fbb738866ba>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type User_user = {
  firstName?: ?string;
  lastName?: ?string;
  intro?: ?string;
  pictureUrl?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "User_user",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "firstName",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "lastName",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "intro",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "pictureUrl",
      "storageKey": null
    }
  ],
  "type": "Person"
};

module.exports = fragment;
